# Generated by Django 3.0.8 on 2021-06-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=70)),
                ('password', models.CharField(max_length=70)),
            ],
        ),
    ]
