# Generated by Django 3.0.8 on 2021-06-07 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210607_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='name',
        ),
    ]
