# Generated by Django 3.0.8 on 2021-06-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_login_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='psw',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='email',
            new_name='uname',
        ),
    ]
