# Generated by Django 3.0.8 on 2021-06-08 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210609_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='password',
            new_name='psw',
        ),
        migrations.RenameField(
            model_name='signin',
            old_name='name',
            new_name='uname',
        ),
    ]
