# Generated by Django 2.1.5 on 2021-07-04 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20210704_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
