# Generated by Django 2.1.5 on 2021-07-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_orders_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id2',
            field=models.CharField(default='123456', max_length=255),
            preserve_default=False,
        ),
    ]
