# Generated by Django 2.1.5 on 2021-07-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_orders_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=255)),
                ('signature', models.CharField(max_length=255)),
                ('order_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Orders')),
            ],
        ),
    ]
