# Generated by Django 2.1.5 on 2021-07-05 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='order_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Orders'),
        ),
    ]
