# Generated by Django 2.1.5 on 2021-07-31 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20210731_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ('-created',), 'verbose_name': 'payment', 'verbose_name_plural': 'payment'},
        ),
        migrations.AddField(
            model_name='payments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
